name: Fusionar

on:
  workflow_dispatch:
    inputs:
      pr:
        description: Número del pull request.
        required: true
        type: number

permissions:
  contents: read

jobs:
  fusionar:
    uses: veriko-mx-labs/.github/.github/workflows/fusionar-como-veriko.yml@eaaa2dca88eec1abbb98d75c8638290a28e0bbbb
    with:
      pr: ${{ fromJSON(inputs.pr) }}
    secrets:
      app_id: ${{ secrets.VERIKO_LABS_APP_ID }}
      app_private_key: ${{ secrets.VERIKO_LABS_PRIVATE_KEY }}
